[tool.poetry]
name = "covid19-vis-demos"
version = "0.1.0"
description = ""
authors = ["Ben Swift <ben.swift@anu.edu.au>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
